# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3606:3606
    environment:
      MYSQL_ROOT_PASSWORD: salewebapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
